### ISSUE TITLE
Open a PR

### ISSUE THREAD

**Issue by anamaria96** [dextermd/Test_SaltEdge#1]
In order to review your code we need to be able to leave you comments. For this, please follow these steps:

1. Create a new branch
2. Rename all your files
3. Commit your changes
4. Open a Pull Request from that branch into master
5. Send us the link to the Pull Request.

After this, we will review your code and give you some feedback.

**Comment by dextermd** [comment]
https://github.com/dextermd/Test_SaltEdge/pull/2

**Comment by dextermd** [comment]
https://github.com/dextermd/Test_SaltEdge/pull/2

пн, 10 февр. 2020 г. в 10:53, Serdiuc Ana-Maria <notifications@github.com>:
